### ISSUE TITLE
Refactor DB configuration

### ISSUE THREAD

**Issue by mpavlase** [rfmvh/perfevents-result-collector#1]
Put credentials and other DB configuration `RESULTDB_*` into separate .conf file

I'd recommend to use configparse module:
https://docs.python.org/2/library/configparser.html

**Comment by rfmvh** [comment]
Seems like to be no extra dependency, thus OK...

**Comment by mpavlase** [comment]
Would be also nice to have an option to load configuration from not-versioned file such "local.conf" that would have precedence to "default.conf".

**Comment by rfmvh** [comment]
Definitelly! The installation process on the testing machines would be then the following: cat the configuration into some local config file and just run the installer script. No `sed -i 's/server/real_server/'` would be necessary anymore.

Also noting that this change will need an extra care when merging to master, since all the tests that install this tool would need to be updated.
